# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataservice/proto/dataservice.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#dataservice/proto/dataservice.proto\x12\x0b\x64\x61taservice\"H\n\x11IngestDataRequest\x12\x11\n\tdatasetId\x18\x01 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\t\x12\x10\n\x08\x66ileName\x18\x03 \x01(\t\"%\n\x12IngestDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32^\n\x0b\x44\x61taService\x12O\n\nIngestData\x12\x1e.dataservice.IngestDataRequest\x1a\x1f.dataservice.IngestDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataservice.proto.dataservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INGESTDATAREQUEST']._serialized_start=52
  _globals['_INGESTDATAREQUEST']._serialized_end=124
  _globals['_INGESTDATARESPONSE']._serialized_start=126
  _globals['_INGESTDATARESPONSE']._serialized_end=163
  _globals['_DATASERVICE']._serialized_start=165
  _globals['_DATASERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
