[tool.poetry]
name = "dataservice"
version = "0.1.0"
description = ""
authors = ["Guilherme <g.lisboa.oliveira@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = {extras = ["s3"], version = "^1.34.79"}
pyarrow = "^15.0.0"
pandas = "^2.1.4"
python-dotenv = "^1.0.0"
grpcio = "^1.62.0"
protobuf = "^4.25.3"
duckdb = "^0.10.0"


[tool.poetry.group.dev.dependencies]
boto3-stubs = {version = "1.34.54", extras = ["s3"]}
pytest = "^8.0.2"
grpcio-tools = "^1.60.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.0.2"
grpcio-testing = "^1.60.0"
pytest-asyncio = "^0.23.5"
coverage = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
relative_files = true
branch = true
command_line = "-m pytest"
source = ["dataservice"]
omit = ["dataservice/proto/*"] # omit generated files

[tool.coverage.report]
show_missing = true
skip_covered = true